### ISSUE TITLE
Project doesn't build on latest Android tools

### ISSUE THREAD

**Issue by roughike** [CodemateLtd/android-architecture-and-testing-sample#1]
It's something about the theming. CoordinatorLayout doesn't like the way the theming works, or something.

**Comment by alexlindroos** [comment]
881b36403902ad99e370a37e8155a2659e1b8ed0 Check the pull request. Fixed here.

**Comment by alexlindroos** [comment]
a796120e38aa8a09f931165c37c0465a75cf1cdc Fix merged to master

**Comment by roughike** [comment]
Thanks!
